-- 최초 스키마 참고용 파일입니다.
-- 현재 프로젝트의 추가 변경은 supabase/migrations 폴더와 Supabase CLI로 관리합니다.
create extension if not exists pgcrypto;

create table if not exists public.poker_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  owner_id uuid not null references auth.users(id) on delete cascade,
  is_open boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.poker_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.poker_rooms(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 20),
  buyin integer not null default 1 check (buyin between 0 and 100),
  created_at timestamptz not null default now(),
  unique (room_id, user_id)
);

-- 동시에 여러 명이 참가해도 한 방에 9명을 넘지 않도록 DB에서 최종 차단합니다.
create or replace function public.enforce_poker_room_player_limit()
returns trigger
language plpgsql
as $$
begin
  perform pg_advisory_xact_lock(hashtext(new.room_id::text));
  if (select count(*) from public.poker_players where room_id = new.room_id) >= 9 then
    raise exception '이 게임 방은 최대 9명까지 참가할 수 있습니다.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists poker_room_player_limit on public.poker_players;
create trigger poker_room_player_limit
before insert on public.poker_players
for each row execute function public.enforce_poker_room_player_limit();

alter table public.poker_rooms enable row level security;
alter table public.poker_players enable row level security;

drop policy if exists "authenticated users can read rooms" on public.poker_rooms;
create policy "authenticated users can read rooms"
on public.poker_rooms for select to authenticated using (true);

drop policy if exists "users can create their own rooms" on public.poker_rooms;
create policy "users can create their own rooms"
on public.poker_rooms for insert to authenticated
with check (owner_id = auth.uid());

drop policy if exists "owners can update rooms" on public.poker_rooms;
create policy "owners can update rooms"
on public.poker_rooms for update to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "owners can delete rooms" on public.poker_rooms;
create policy "owners can delete rooms"
on public.poker_rooms for delete to authenticated
using (owner_id = auth.uid());

drop policy if exists "authenticated users can read players" on public.poker_players;
create policy "authenticated users can read players"
on public.poker_players for select to authenticated using (true);

drop policy if exists "players and room owners can join" on public.poker_players;
create policy "players and room owners can join"
on public.poker_players for insert to authenticated
with check (
  (user_id = auth.uid() and exists (
    select 1 from public.poker_rooms r where r.id = room_id and r.is_open
  ))
  or exists (
    select 1 from public.poker_rooms r where r.id = room_id and r.owner_id = auth.uid()
  )
);

drop policy if exists "players can update themselves and owners can manage" on public.poker_players;
create policy "players can update themselves and owners can manage"
on public.poker_players for update to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.poker_rooms r where r.id = room_id and r.owner_id = auth.uid())
)
with check (
  user_id = auth.uid()
  or exists (select 1 from public.poker_rooms r where r.id = room_id and r.owner_id = auth.uid())
);

drop policy if exists "room owners can delete players" on public.poker_players;
create policy "room owners can delete players"
on public.poker_players for delete to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.poker_rooms r where r.id = room_id and r.owner_id = auth.uid())
);

-- Dashboard > Authentication > Providers에서 Anonymous Sign-Ins도 활성화하세요.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'poker_players'
  ) then
    alter publication supabase_realtime add table public.poker_players;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'poker_rooms'
  ) then
    alter publication supabase_realtime add table public.poker_rooms;
  end if;
end $$;
