alter table public.poker_rooms
  add column if not exists current_level integer not null default 0 check (current_level between 0 and 16),
  add column if not exists timer_running boolean not null default false,
  add column if not exists timer_ends_at timestamptz,
  add column if not exists timer_remaining_ms bigint not null default 420000 check (timer_remaining_ms >= 0),
  add column if not exists rebuy_until_stage integer not null default 4 check (rebuy_until_stage between 0 and 16),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.poker_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.poker_rooms(id) on delete cascade,
  player_id bigint references public.poker_players(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  player_name text not null,
  event_type text not null check (event_type in ('join', 'rebuy', 'rebuy_undo')),
  buyin_before integer,
  buyin_after integer,
  reversed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.poker_events enable row level security;

create or replace function public.log_poker_player_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.poker_events
      (room_id, player_id, user_id, player_name, event_type, buyin_before, buyin_after)
    values
      (new.room_id, new.id, new.user_id, new.name, 'join', 0, new.buyin);
  elsif tg_op = 'UPDATE' and new.buyin is distinct from old.buyin then
    insert into public.poker_events
      (room_id, player_id, user_id, player_name, event_type, buyin_before, buyin_after)
    values
      (new.room_id, new.id, new.user_id, new.name,
       case when new.buyin > old.buyin then 'rebuy' else 'rebuy_undo' end,
       old.buyin, new.buyin);
  end if;
  return new;
end;
$$;

drop trigger if exists poker_player_event_log on public.poker_players;
create trigger poker_player_event_log
after insert or update of buyin on public.poker_players
for each row execute function public.log_poker_player_event();

create or replace function public.change_poker_buyin(p_player_id bigint, p_delta integer)
returns public.poker_players
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.poker_players;
  v_room public.poker_rooms;
begin
  if p_delta not in (-1, 1) then
    raise exception '바인 변경값은 1 또는 -1이어야 합니다.';
  end if;

  select * into v_player from public.poker_players where id = p_player_id for update;
  if not found then raise exception '참가자를 찾을 수 없습니다.'; end if;
  select * into v_room from public.poker_rooms where id = v_player.room_id;

  if v_room.created_at < now() - interval '12 hours' then
    raise exception '만료된 게임 방입니다.';
  end if;
  if auth.uid() <> v_room.owner_id and auth.uid() is distinct from v_player.user_id then
    raise exception '본인의 바인만 변경할 수 있습니다.';
  end if;
  if auth.uid() <> v_room.owner_id and p_delta <> 1 then
    raise exception '참가자는 리바인 취소를 직접 할 수 없습니다.';
  end if;
  if p_delta = 1 and v_room.current_level > v_room.rebuy_until_stage then
    raise exception '리바인 마감 레벨이 지났습니다.';
  end if;
  if p_delta = -1 and v_player.buyin <= 0 then
    raise exception '바인 횟수는 0보다 작을 수 없습니다.';
  end if;

  update public.poker_players
  set buyin = buyin + p_delta
  where id = p_player_id
  returning * into v_player;
  return v_player;
end;
$$;

create or replace function public.undo_poker_rebuy(p_event_id bigint)
returns public.poker_players
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.poker_events;
  v_player public.poker_players;
begin
  select * into v_event from public.poker_events where id = p_event_id for update;
  if not found or v_event.event_type <> 'rebuy' or v_event.reversed_at is not null then
    raise exception '취소할 수 없는 리바인 기록입니다.';
  end if;
  if not exists (
    select 1 from public.poker_rooms r where r.id = v_event.room_id and r.owner_id = auth.uid()
  ) then
    raise exception '방 관리자만 리바인을 취소할 수 있습니다.';
  end if;

  update public.poker_players
  set buyin = greatest(0, buyin - 1)
  where id = v_event.player_id and buyin > 0
  returning * into v_player;
  if not found then raise exception '참가자 또는 바인 기록을 찾을 수 없습니다.'; end if;

  update public.poker_events set reversed_at = now() where id = p_event_id;
  return v_player;
end;
$$;

revoke all on function public.change_poker_buyin(bigint, integer) from public;
revoke all on function public.undo_poker_rebuy(bigint) from public;
grant execute on function public.change_poker_buyin(bigint, integer) to authenticated;
grant execute on function public.undo_poker_rebuy(bigint) to authenticated;

drop policy if exists "room members can read events" on public.poker_events;
create policy "room members can read events"
on public.poker_events for select to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.poker_rooms r where r.id = room_id and r.owner_id = auth.uid())
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'poker_events'
  ) then
    alter publication supabase_realtime add table public.poker_events;
  end if;
end $$;

create extension if not exists pg_cron with schema pg_catalog;

select cron.schedule(
  'cleanup-stale-poker-rooms',
  '*/15 * * * *',
  $cleanup$delete from public.poker_rooms where created_at < now() - interval '12 hours'$cleanup$
);
